import { createSchema } from "@ponder/core";

export default createSchema((p) => ({
  OptionContract: p.createTable({
    id: p.string(),
    address: p.string(),
    token0: p.string(),
    token1: p.string(),
    isPaused: p.boolean(),
    poolContract: p.bytes(),
    routerContract: p.bytes(),
    pool: p.string(),
    asset: p.string(),
    openUp: p.bigint(),
    openDown: p.bigint(),
    configId: p.string().references("ConfigContract.id"),
    configContract: p.one("configId"),
  }),
  ConfigContract: p.createTable({
    id: p.string(),
    address: p.string(),
    minFee: p.bigint(),
    creationWindowContract: p.bytes(),
    circuitBreakerContract: p.bytes(),
    optionStorageContract: p.bytes(),
    platformFee: p.bigint(),
    sfdContract: p.bytes(),
    sf: p.bigint(),
    tradeNFTContract: p.bytes(),
    stepSize: p.bigint(),
  }),
  QueuedOptionData: p.createTable({
    id: p.string(),
    optionContractId: p.string().references("OptionContract.id"),
    optionContract: p.one("optionContractId"),
    strike: p.bigint(),
    user: p.string(),
    state: p.int(),
    isAbove: p.boolean(),
    queueId: p.bigint(),
    reason: p.string().optional(),
    queueTimestamp: p.bigint(),
    cancelTimestamp: p.bigint(),
    lag: p.bigint(),
    processTime: p.bigint(),
    expirationTime: p.bigint(),
    totalFee: p.bigint(),
  }),
  UserOptionData: p.createTable({
    id: p.string(),
    optionContractId: p.string().references("OptionContract.id"),
    optionContract: p.one("optionContractId"),
    optionID: p.bigint(),
    strike: p.bigint().optional(),
    totalFee: p.bigint(),
    user: p.string(),
    creationTime: p.bigint().optional(),
    queuedTimestamp: p.bigint(),
    expirationPrice: p.bigint().optional(),
    payout: p.bigint().optional(),
    state: p.int(),
    amount: p.bigint(),
    expirationTime: p.bigint().optional(),
    isAbove: p.boolean().optional(),
    queueID: p.bigint().optional(),
    settlementFee: p.bigint().optional(),
    lag: p.bigint(),
    depositToken: p.string().optional(),
    payoutUSD: p.bigint().optional(),
    totalFeeUSD: p.bigint().optional(),
  }),
}));
